name: bootstrap_sass
version: 5.0.2
description: Sass source files to create bootstrap themes
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/luisvt/bootstrap_sass
environment:
  sdk: '>=2.17.0 <4.0.0'
dev_dependencies:
  sass_builder: ^2.0.0
  build_runner: any
  build_test: any
  build_web_compilers: any
