name: bootstrap_sass
version: 3.3.6
description: Sass source files to create bootstrap themes
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/luisvt/bootstrap_sass
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  sass:
transformers:
- sass